/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119331-g3bb2b8aff4-20250422"
#endif /* AVUTIL_FFVERSION_H */
